//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class absence_request
    {
        public string employee_id { get; set; }

        [Key]
        public string id { get; set; }
        public Nullable<System.DateTime> ask_date { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<sbyte> timeoff_type_id { get; set; }
        public Nullable<sbyte> status { get; set; }
        public string approve_man_id { get; set; }
    }
}
