//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class accrual
    {
        [Key]
        public string id { get; set; }
        public string plan_name { get; set; }
        public Nullable<sbyte> timeoff_type_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> enforced_date { get; set; }
        public Nullable<System.DateTime> amount_date { get; set; }
        public Nullable<sbyte> period { get; set; }
        public string unit { get; set; }
        public Nullable<sbyte> limit { get; set; }
        public Nullable<sbyte> proccess_code_for_remain_days { get; set; }
    }
}
