//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class applicant
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string department_id { get; set; }
        public string title_id { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<sbyte> degree_id { get; set; }
        public string college { get; set; }
        public Nullable<double> require_wage { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public string interviewer_id { get; set; }
        public Nullable<sbyte> status { get; set; }
        public Nullable<double> ultimate_wage { get; set; }


        [Key]
        public string id { get; set; }
    }
}
