//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class employee
    {
        [Key]
        public string id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string title_id { get; set; }
        public string phone { get; set; }
        public string department_id { get; set; }
        public string manager_id { get; set; }
        public string timeoff_manager_id { get; set; }
        public string expense_manager_id { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public Nullable<double> distance_from_home { get; set; }
        public string identity_citizen_id { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string born_place { get; set; }
        public Nullable<sbyte> martial_status_id { get; set; }
        public Nullable<sbyte> number_of_children { get; set; }
        public string emergency_contact_man { get; set; }
        public string emergency_phone { get; set; }
        public Nullable<sbyte> degree_id { get; set; }
        public string major { get; set; }
        public string college { get; set; }
        public string bank_account { get; set; }
    }
}
