//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class experience_education
    {
        [Key]
        [Column(Order = 1)]
        public string id { get; set; }
        [Key]
        [Column(Order = 2)]
        public string organization_name { get; set; }
        [Key]
        [Column(Order = 3)]
        public string project_or_description { get; set; }
        public string skill { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    }
}
