//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class expense_report
    {
        [Key]
        public string report_id { get; set; }
        public string report_name { get; set; }
        public string approve_man_id { get; set; }
        public string pay_man_id { get; set; }
        public Nullable<sbyte> status { get; set; }
        public string employee_id { get; set; }
    }
}
