//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class expense
    {
        [Key]
        [Column(Order = 1)]
        public string product_id { get; set; }
        public Nullable<double> price_per_item { get; set; }
        public string unit { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> total_value { get; set; }
        [Key]
        [Column(Order = 2)]
        public System.DateTime expense_date { get; set; }

        [Key]
        [Column(Order = 3)]
        public string employee_id { get; set; }
        public string id { get; set; }
    }
}
