//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration.Conventions;

    public partial class hrmEntities1 : DbContext
    {
        public hrmEntities1()
            : base("name=hrmEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            base.OnModelCreating(modelBuilder);
            // throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<absence> absences { get; set; }
        public virtual DbSet<absence_request> absence_request { get; set; }
        public virtual DbSet<accrual> accruals { get; set; }
        public virtual DbSet<applicant> applicants { get; set; }
        public virtual DbSet<contract> contracts { get; set; }
        public virtual DbSet<degree> degrees { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<expense> expenses { get; set; }
        public virtual DbSet<expense_report> expense_report { get; set; }
        public virtual DbSet<experience_education> experience_education { get; set; }
        public virtual DbSet<material_status> material_status { get; set; }
        public virtual DbSet<plan> plans { get; set; }
        public virtual DbSet<plan_activities> plan_activities { get; set; }
        public virtual DbSet<plan_for_employee> plan_for_employee { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<requirements_for_job> requirements_for_job { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<skill> skills { get; set; }
        public virtual DbSet<skill_of_employee> skill_of_employee { get; set; }
        public virtual DbSet<skill_type> skill_type { get; set; }
        public virtual DbSet<standard_work_time> standard_work_time { get; set; }
        public virtual DbSet<standard_work_time_for_employee> standard_work_time_for_employee { get; set; }
        public virtual DbSet<time_off> time_off { get; set; }
        public virtual DbSet<timeoff_type> timeoff_type { get; set; }
        public virtual DbSet<title> titles { get; set; }
        public virtual DbSet<title_recruit> title_recruit { get; set; }
        public virtual DbSet<work_time> work_time { get; set; }
        public virtual DbSet<expenses_in_report> expenses_in_report { get; set; }
        public virtual DbSet<n_absence> n_absence { get; set; }
        public virtual DbSet<n_extra_work_time> n_extra_work_time { get; set; }
        public virtual DbSet<n_number_product> n_number_product { get; set; }
        public virtual DbSet<n_product> n_product { get; set; }
        public virtual DbSet<n_restrict_product> n_restrict_product { get; set; }
        public virtual DbSet<n_holiday> n_holiday { get; set; }
    }
}
