//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class plan_activities
    {
        [Key]
        [Column(Order = 1)]
        public string plan_id { get; set; }
        [Key]
        [Column(Order = 2)]
        public string job_name { get; set; }
        public Nullable<sbyte> conduct_role_id { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
    }
}
