//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class product
    {
        [Key]
        public string id { get; set; }
        public string product_name { get; set; }
        public Nullable<double> proposed_price { get; set; }
        public string unit_1 { get; set; }
        public Nullable<double> sale_price { get; set; }
        public string unit_2 { get; set; }
        public string prefix_code { get; set; }
        public Nullable<sbyte> vendor_tax { get; set; }
        public Nullable<sbyte> customer_tax { get; set; }
    }
}
