//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class title_recruit
    {
        [Key]
        [Column(Order = 1)]
        public string title_id { get; set; }
        public Nullable<sbyte> slot { get; set; }

        [Key]
        [Column(Order = 2)]
        public string department_id { get; set; }
        public string recruiter { get; set; }
    }
}
